#!/usr/bin/env python3
"""Generate web-ready WebP derivatives + LQIP data URIs from the raw photos.

Outputs:
  site/assets/photos/<slug>-1200.webp   grid / lightbox on small screens
  site/assets/photos/<slug>-2400.webp   full-bleed + lightbox on large screens
  site/js/photos.js                     manifest consumed by the site
"""
import base64
import io
import json
import os
import re

from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "site", "assets", "photos")
os.makedirs(OUT, exist_ok=True)

with open(os.path.join(ROOT, "tools", "manifest.json")) as fh:
    items = json.load(fh)

WIDTHS = [1200, 2400]
records = []

for n, item in enumerate(items, 1):
    src = os.path.join(ROOT, item["src"])
    if not os.path.exists(src):
        print(f"  !! missing {item['src']}")
        continue

    im = Image.open(src)
    im = im.convert("RGB")
    w, h = im.size

    for target in WIDTHS:
        dest = os.path.join(OUT, f"{item['slug']}-{target}.webp")
        if os.path.exists(dest) and os.path.getmtime(dest) > os.path.getmtime(src):
            continue
        # Scale on the *long* edge so tall frames stay generous too.
        scale = target / max(w, h)
        if scale >= 1:
            out = im.copy()
        else:
            out = im.resize((round(w * scale), round(h * scale)), Image.LANCZOS)
        quality = 82 if target == 1200 else 78
        out.save(dest, "WEBP", quality=quality, method=6)

    # LQIP: a 20px blurred thumb inlined as a data URI, so a frame never
    # flashes empty while its WebP streams in.
    lq = im.copy()
    lq.thumbnail((20, 20), Image.LANCZOS)
    lq = lq.filter(ImageFilter.GaussianBlur(0.6))
    buf = io.BytesIO()
    lq.save(buf, "WEBP", quality=45)
    lqip = "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode()

    records.append({
        "slug": item["slug"],
        "title": item["title"],
        "cat": item["cat"],
        "place": item["place"],
        "year": item["year"],
        "w": w,
        "h": h,
        "ratio": round(w / h, 4),
        "orient": "portrait" if h > w * 1.04 else ("square" if abs(w - h) < w * 0.04 else "landscape"),
        "lqip": lqip,
    })
    print(f"  [{n:02d}/{len(items)}] {item['slug']}  {w}x{h}")

js = os.path.join(ROOT, "site", "js", "photos.js")
with open(js, "w") as fh:
    fh.write("// Generated by tools/build-images.py. Do not edit by hand.\n")
    fh.write("export const PHOTOS = ")
    json.dump(records, fh, indent=1, ensure_ascii=False)
    fh.write(";\n")

# Write a plain, complete version of the grid straight into the HTML. main.js
# swaps it for the art-directed, filterable one, but this is what search
# engines and no-JS visitors get, and it keeps every photo's alt text in the
# served markup rather than behind a script.
def escape(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;")
             .replace(">", "&gt;").replace('"', "&quot;"))


cells = []
for r in records:
    alt = escape(r["place"])
    cells.append(
        f'      <figure class="cell" data-span="4">\n'
        f'        <span class="cell__media" style="aspect-ratio:{r["ratio"]}">\n'
        f'          <img src="assets/photos/{r["slug"]}-1200.webp"\n'
        f'               srcset="assets/photos/{r["slug"]}-1200.webp 1200w,'
        f' assets/photos/{r["slug"]}-2400.webp 2400w"\n'
        f'               sizes="(max-width: 900px) 92vw, 31vw"\n'
        f'               alt="{alt}" width="{r["w"]}" height="{r["h"]}"\n'
        f'               loading="lazy" decoding="async" />\n'
        f'        </span>\n'
        f'      </figure>'
    )

html_path = os.path.join(ROOT, "site", "index.html")
with open(html_path) as fh:
    html = fh.read()
start, end = "<!-- grid:start -->", "<!-- grid:end -->"
a, b = html.index(start) + len(start), html.index(end)
html = html[:a] + "\n" + "\n".join(cells) + "\n      " + html[b:]

with open(html_path, "w") as fh:
    fh.write(html)
print(f"static grid: {len(cells)} figures written into site/index.html")

# Drop derivatives for photos no longer in the manifest, so removing an entry
# does not leave orphaned files in the deployed folder.
live = {f"{r['slug']}-{w}.webp" for r in records for w in WIDTHS}
orphans = [f for f in os.listdir(OUT) if f.endswith(".webp") and f not in live]
for f in orphans:
    os.remove(os.path.join(OUT, f))
if orphans:
    print(f"pruned {len(orphans)} orphaned derivative(s)")

total = sum(
    os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT) if f.endswith(".webp")
)
print(f"\n{len(records)} photos -> {len(records) * 2} webp files, {total / 1e6:.1f} MB total")
print(f"manifest: {js}")
